### ISSUE TITLE
Files need reorganizing & file names need fixed.

### ISSUE THREAD

**Issue by break-core** [NTx86/RBXGSdecomp#1]
Title speaks for itself, but file names must be fixed.

## Ideas with fixing file names
Currently, they are all lowercase. However, this is not accurate to the actual code. You can find the accurate names by searching for the S_COMPILE2 data for the code obj in a PDB dump. There is a value called `src` which displays the source path for the code (which shows the original name un-lowercased).

## Ideas with reorganizing files
Next up is file organizing. My idea for this is to have `App`, `Network`, `Rendering`, etc. all in the root of the GitHub repository. Or there could be a single `Client` folder in the repository which holds `App`, `Network`, `Rendering`, etc. like how Roblox does it, and then outside of the `Client` folder there could be stuff like the project file, the readme, etc.

**Comment by KeyboardCombination** [comment]
I agree with these changes, the disorganization in terms of directories is merely from Visual Studio's utilization of "Filters" instead of actual folders, which absolutely will be adjusted accordingly. Will consider moving everything that is decompiled code into an App directory as per the original source, will likely have directories for code handling v8kernel/v8world as its own dependency compared to the full structure to satisfy the current scope.

**Comment by KeyboardCombination** [comment]
done now
